// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: billing/paymentsapi/v1/api.proto

package paymentsapiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPaymentMethodRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentMethodId string                 `protobuf:"bytes,1,opt,name=paymentMethodId,proto3" json:"paymentMethodId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetPaymentMethodRequest) Reset() {
	*x = GetPaymentMethodRequest{}
	mi := &file_billing_paymentsapi_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentMethodRequest) ProtoMessage() {}

func (x *GetPaymentMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_paymentsapi_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentMethodRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentMethodRequest) Descriptor() ([]byte, []int) {
	return file_billing_paymentsapi_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetPaymentMethodRequest) GetPaymentMethodId() string {
	if x != nil {
		return x.PaymentMethodId
	}
	return ""
}

type GetPaymentMethodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsPrimary     bool                   `protobuf:"varint,1,opt,name=isPrimary,proto3" json:"isPrimary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentMethodResponse) Reset() {
	*x = GetPaymentMethodResponse{}
	mi := &file_billing_paymentsapi_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentMethodResponse) ProtoMessage() {}

func (x *GetPaymentMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_paymentsapi_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentMethodResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentMethodResponse) Descriptor() ([]byte, []int) {
	return file_billing_paymentsapi_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetPaymentMethodResponse) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

var File_billing_paymentsapi_v1_api_proto protoreflect.FileDescriptor

const file_billing_paymentsapi_v1_api_proto_rawDesc = "" +
	"\n" +
	" billing/paymentsapi/v1/api.proto\x12\x16billing.paymentsapi.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bbuf/validate/validate.proto\"M\n" +
	"\x17GetPaymentMethodRequest\x122\n" +
	"\x0fpaymentMethodId\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x0fpaymentMethodId\"A\n" +
	"\x18GetPaymentMethodResponse\x12%\n" +
	"\tisPrimary\x18\x01 \x01(\bB\a\xbaH\x04j\x02\b\x01R\tisPrimary2\xb0\x01\n" +
	"\vPaymentsAPI\x12\xa0\x01\n" +
	"\x10GetPaymentMethod\x12/.billing.paymentsapi.v1.GetPaymentMethodRequest\x1a0.billing.paymentsapi.v1.GetPaymentMethodResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/payments/{paymentMethodId}B\xe0\x01\n" +
	"\x1acom.billing.paymentsapi.v1B\bApiProtoP\x01Z>libs/backend/proto-gen/go/billing/paymentsapi/v1;paymentsapiv1\xa2\x02\x03BPX\xaa\x02\x16Billing.Paymentsapi.V1\xca\x02\x16Billing\\Paymentsapi\\V1\xe2\x02\"Billing\\Paymentsapi\\V1\\GPBMetadata\xea\x02\x18Billing::Paymentsapi::V1b\x06proto3"

var (
	file_billing_paymentsapi_v1_api_proto_rawDescOnce sync.Once
	file_billing_paymentsapi_v1_api_proto_rawDescData []byte
)

func file_billing_paymentsapi_v1_api_proto_rawDescGZIP() []byte {
	file_billing_paymentsapi_v1_api_proto_rawDescOnce.Do(func() {
		file_billing_paymentsapi_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_paymentsapi_v1_api_proto_rawDesc), len(file_billing_paymentsapi_v1_api_proto_rawDesc)))
	})
	return file_billing_paymentsapi_v1_api_proto_rawDescData
}

var file_billing_paymentsapi_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_billing_paymentsapi_v1_api_proto_goTypes = []any{
	(*GetPaymentMethodRequest)(nil),  // 0: billing.paymentsapi.v1.GetPaymentMethodRequest
	(*GetPaymentMethodResponse)(nil), // 1: billing.paymentsapi.v1.GetPaymentMethodResponse
}
var file_billing_paymentsapi_v1_api_proto_depIdxs = []int32{
	0, // 0: billing.paymentsapi.v1.PaymentsAPI.GetPaymentMethod:input_type -> billing.paymentsapi.v1.GetPaymentMethodRequest
	1, // 1: billing.paymentsapi.v1.PaymentsAPI.GetPaymentMethod:output_type -> billing.paymentsapi.v1.GetPaymentMethodResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_billing_paymentsapi_v1_api_proto_init() }
func file_billing_paymentsapi_v1_api_proto_init() {
	if File_billing_paymentsapi_v1_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_paymentsapi_v1_api_proto_rawDesc), len(file_billing_paymentsapi_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_paymentsapi_v1_api_proto_goTypes,
		DependencyIndexes: file_billing_paymentsapi_v1_api_proto_depIdxs,
		MessageInfos:      file_billing_paymentsapi_v1_api_proto_msgTypes,
	}.Build()
	File_billing_paymentsapi_v1_api_proto = out.File
	file_billing_paymentsapi_v1_api_proto_goTypes = nil
	file_billing_paymentsapi_v1_api_proto_depIdxs = nil
}
