version: '3.9'
name: challah-social
services:
  ############ KONG API GATEWAY/REVERSE PROXY ############
  kong-api-gateway:
    image: challah-social/kong-api-gateway
    container_name: challah-social-kong-api-gateway
    build:
      context: .
      dockerfile: ./apps/services/kong-api-gateway/Dockerfile
      args:
        - INBOUND_WEBHOOKS_API_URL=http://inbound-webhooks-api:3000
    restart: always
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      - 8003:8003
      - 8004:8004
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
      - KONG_LICENSE_DATA=
  ############ /KONG API GATEWAY/REVERSE PROXY ############

  ############ INBOUND WEBHOOKS API ############
  inbound-webhooks-api:
    image: challah-social/inbound-webhooks-api
    container_name: challah-social-inbound-webhooks-api
    build:
      context: .
      dockerfile: ./apps/services/inbound-webhooks-api/Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./apps/services/inbound-webhooks-api/.env.local
    volumes:
      - inbound-webhooks-api:/app
    depends_on:
      - lavinmq
  ############ /INBOUND WEBHOOKS API ############

  ############ ACCOUNTS API ############
  accounts-api:
    image: challah-social/accounts-api
    container_name: challah-social-accounts-api
    build:
      context: .
      dockerfile: ./apps/services/accounts-api/Dockerfile
    ports:
      - 3001:3000
    env_file:
      - ./apps/services/accounts-api/.env.local
    volumes:
      - accounts-api:/app
    depends_on:
      - inbound-webhooks-api
      - cockroachdb-cluster
  ############ /ACCOUNTS API ############

  ############ ACCOUNTS WORKER ############
  accounts-worker:
    image: challah-social/accounts-worker
    container_name: challah-social-accounts-worker
    build:
      context: .
      dockerfile: ./apps/services/accounts-worker/Dockerfile
    ports:
      - 3002:3000
    env_file:
      - ./apps/services/accounts-worker/.env.local
    volumes:
      - accounts-worker:/app
    depends_on:
      - inbound-webhooks-api
  ############ /ACCOUNTS WORKER ############

  ############ ACCOUNTS GRAPHQL ############
  accounts-graphql:
    image: challah-social/accounts-graphql
    container_name: challah-social-accounts-graphql
    build:
      context: .
      dockerfile: ./apps/services/accounts-graphql/Dockerfile
    ports:
      - 3003:3000
    env_file:
      - ./apps/services/accounts-graphql/.env.local
    volumes:
      - accounts-graphql:/app
    depends_on:
      - inbound-webhooks-api
      - accounts-api
      - cockroachdb-cluster
  ############ /ACCOUNTS GRAPHQL ############

  ############ PROFILE API ############
  profile-api:
    image: challah-social/profile-api
    container_name: challah-social-profile-api
    build:
      context: .
      dockerfile: ./apps/services/profile-api/Dockerfile
    ports:
      - 3004:3000
    env_file:
      - ./apps/services/profile-api/.env.local
    volumes:
      - profile-api:/app
    depends_on:
      - inbound-webhooks-api
      - cockroachdb-cluster
  ############ /PROFILE API ############

  ############ LAVINMQ ############
  lavinmq:
    image: cloudamqp/lavinmq:latest
    container_name: lavinmq
    hostname: lavinmq
    ports:
      - 15672:15672 # Management UI
      - 5672:5672 # AMQP
    restart: always
  ############ /LAVINMQ ############

  ############ CockroachDB Cluser ############
  cockroachdb-cluster:
    image: cockroachdb/cockroach
    ports:
      - '26257:26257'
      - '9876:8080'
    command: start-single-node --insecure
    volumes:
      - cockroachdb-cluster:/cockroach/cockroach-data'
      - ./docker-startup/db:/docker-entrypoint-initdb.d
    restart: always
  ############ /CockroachDB Cluser ############

  ############ Apollo Router ############
  apollo-router:
    image: ghcr.io/apollographql/router:v1.59.0
    container_name: apollo-router
    ports:
      - '4000:4000'
    env_file:
      - ./apps/services/apollo-router/.env.local
    volumes:
      - ./graphql/supergraph-dev.yaml:/supergraph.yaml
      - ./graphql/supergraph-dev.graphql:/supergraph.graphql
      - ./graphql/router-dev.yaml:/router.yaml
    command:
      [
        '--dev',
        '--config',
        '/router.yaml',
        '--supergraph',
        '/supergraph.graphql',
      ]
    depends_on:
      - accounts-graphql
  ############ /Apollo Router ############
volumes:
  inbound-webhooks-api:
  accounts-api:
  accounts-worker:
  accounts-graphql:
  profile-api:
  lavinmq:
  cockroachdb-cluster:
