# fly.toml app configuration file generated for apollo-router-prod on 2025-01-01T21:52:28-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'apollo-router-prod'
primary_region = 'ewr'

[build]
dockerfile = 'Dockerfile'

[http_service]
internal_port = 4000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
