apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: accounts-api-ingress
  namespace: default
  annotations:
    konghq.com/strip-path: "true"  # Ensures Kong forwards clean paths
spec:
  ingressClassName: kong
  rules:
    - host: accounts-api  # Replace with your domain or internal hostname
      http:
        paths:
          - path: /accounts
            pathType: Prefix
            backend:
              service:
                name: accounts-api  # Must match the ClusterIP service name
                port:
                  number: 9090
