// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: accounts/accountsevents/v1/events.proto

package accountseventsv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserRegistered defines the incoming data for the user created event from
// Auth0 Actions after the user has registered for the first time
type UserRegistered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	EmailAddress  string                 `protobuf:"bytes,4,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	ClerkUserId   string                 `protobuf:"bytes,5,opt,name=clerk_user_id,json=clerkUserId,proto3" json:"clerk_user_id,omitempty"`
	Gender        string                 `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRegistered) Reset() {
	*x = UserRegistered{}
	mi := &file_accounts_accountsevents_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegistered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegistered) ProtoMessage() {}

func (x *UserRegistered) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_accountsevents_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegistered.ProtoReflect.Descriptor instead.
func (*UserRegistered) Descriptor() ([]byte, []int) {
	return file_accounts_accountsevents_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *UserRegistered) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserRegistered) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserRegistered) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserRegistered) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

func (x *UserRegistered) GetClerkUserId() string {
	if x != nil {
		return x.ClerkUserId
	}
	return ""
}

func (x *UserRegistered) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

var File_accounts_accountsevents_v1_events_proto protoreflect.FileDescriptor

const file_accounts_accountsevents_v1_events_proto_rawDesc = "" +
	"\n" +
	"'accounts/accountsevents/v1/events.proto\x12\x1aaccounts.accountsevents.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/protobuf/any.proto\x1a\x1bbuf/validate/validate.proto\"\xf6\x01\n" +
	"\x0eUserRegistered\x12&\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tfirstName\x12$\n" +
	"\tlast_name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\blastName\x12#\n" +
	"\busername\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\busername\x12,\n" +
	"\remail_address\x18\x04 \x01(\tB\a\xbaH\x04r\x02`\x01R\femailAddress\x12+\n" +
	"\rclerk_user_id\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vclerkUserId\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\tR\x06genderB\xfe\x01\n" +
	"\x1ecom.accounts.accountsevents.v1B\vEventsProtoP\x01ZElibs/backend/proto-gen/go/accounts/accountsevents/v1;accountseventsv1\xa2\x02\x03AAX\xaa\x02\x1aAccounts.Accountsevents.V1\xca\x02\x1aAccounts\\Accountsevents\\V1\xe2\x02&Accounts\\Accountsevents\\V1\\GPBMetadata\xea\x02\x1cAccounts::Accountsevents::V1b\x06proto3"

var (
	file_accounts_accountsevents_v1_events_proto_rawDescOnce sync.Once
	file_accounts_accountsevents_v1_events_proto_rawDescData []byte
)

func file_accounts_accountsevents_v1_events_proto_rawDescGZIP() []byte {
	file_accounts_accountsevents_v1_events_proto_rawDescOnce.Do(func() {
		file_accounts_accountsevents_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_accounts_accountsevents_v1_events_proto_rawDesc), len(file_accounts_accountsevents_v1_events_proto_rawDesc)))
	})
	return file_accounts_accountsevents_v1_events_proto_rawDescData
}

var file_accounts_accountsevents_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_accounts_accountsevents_v1_events_proto_goTypes = []any{
	(*UserRegistered)(nil), // 0: accounts.accountsevents.v1.UserRegistered
}
var file_accounts_accountsevents_v1_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_accounts_accountsevents_v1_events_proto_init() }
func file_accounts_accountsevents_v1_events_proto_init() {
	if File_accounts_accountsevents_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_accounts_accountsevents_v1_events_proto_rawDesc), len(file_accounts_accountsevents_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_accounts_accountsevents_v1_events_proto_goTypes,
		DependencyIndexes: file_accounts_accountsevents_v1_events_proto_depIdxs,
		MessageInfos:      file_accounts_accountsevents_v1_events_proto_msgTypes,
	}.Build()
	File_accounts_accountsevents_v1_events_proto = out.File
	file_accounts_accountsevents_v1_events_proto_goTypes = nil
	file_accounts_accountsevents_v1_events_proto_depIdxs = nil
}
