# fly.toml app configuration file generated for kong-api-gateway-prod-challah-social on 2025-01-31T17:20:01-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kong-api-gateway-prod-challah-social'
primary_region = 'iad'

[build]
dockerfile = 'Dockerfile'

[env]
INBOUND_WEBHOOKS_API_URL = "http://inbound-webhooks-api-prod-challah-social:3000"
KONG_DATABASE = "off"
KONG_DECLARATIVE_CONFIG = "/kong/declarative/kong.yml"
KONG_PROXY_ACCESS_LOG = "/dev/stdout"
KONG_ADMIN_ACCESS_LOG = "/dev/stdout"
KONG_PROXY_ERROR_LOG = "/dev/stderr"
KONG_ADMIN_ERROR_LOG = "/dev/stderr"
# KONG_ADMIN_LISTEN = "0.0.0.0:8001"
# KONG_ADMIN_GUI_URL = "http://localhost:8002"
KONG_LICENSE_DATA = ""

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
