apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullname }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.fullname }}
  template:
    metadata:
      labels:
        app: {{ .Values.fullname }}
    spec:
      containers:
        - name: '{{ .Values.fullname }}'
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Never" }} # Prevent Kubernetes from pulling the image
