// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: accounts/accountsapi/v1/api.proto

package accountsapiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/type/datetime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	domain "libs/backend/proto-gen/go/accounts/domain"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateAccountRequest defines the incoming data for the create account request
type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	EmailAddress  string                 `protobuf:"bytes,4,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	ClerkUserId   string                 `protobuf:"bytes,5,opt,name=clerk_user_id,json=clerkUserId,proto3" json:"clerk_user_id,omitempty"`
	Gender        string                 `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_accounts_accountsapi_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_accountsapi_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_accounts_accountsapi_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateAccountRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateAccountRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateAccountRequest) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

func (x *CreateAccountRequest) GetClerkUserId() string {
	if x != nil {
		return x.ClerkUserId
	}
	return ""
}

func (x *CreateAccountRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

// CreateAcountResponse defines the response for the create account request
type CreateAcountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAcountResponse) Reset() {
	*x = CreateAcountResponse{}
	mi := &file_accounts_accountsapi_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAcountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAcountResponse) ProtoMessage() {}

func (x *CreateAcountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_accountsapi_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAcountResponse.ProtoReflect.Descriptor instead.
func (*CreateAcountResponse) Descriptor() ([]byte, []int) {
	return file_accounts_accountsapi_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAcountResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

// GetAccountRequest defines the incoming data for the get account request
type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommonId      *string                `protobuf:"bytes,1,opt,name=common_id,json=commonId,proto3,oneof" json:"common_id,omitempty"`
	EmailAddress  *string                `protobuf:"bytes,2,opt,name=email_address,json=emailAddress,proto3,oneof" json:"email_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_accounts_accountsapi_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_accountsapi_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_accounts_accountsapi_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetAccountRequest) GetCommonId() string {
	if x != nil && x.CommonId != nil {
		return *x.CommonId
	}
	return ""
}

func (x *GetAccountRequest) GetEmailAddress() string {
	if x != nil && x.EmailAddress != nil {
		return *x.EmailAddress
	}
	return ""
}

// GetAccountResponse defines the response for the get account request
type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *domain.Account        `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_accounts_accountsapi_v1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_accountsapi_v1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_accounts_accountsapi_v1_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccountResponse) GetAccount() *domain.Account {
	if x != nil {
		return x.Account
	}
	return nil
}

// DeleteAccountRequest will hard/soft delete an account by common_id
type DeleteAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommonId      string                 `protobuf:"bytes,1,opt,name=common_id,json=commonId,proto3" json:"common_id,omitempty"`
	HardDelete    bool                   `protobuf:"varint,2,opt,name=hard_delete,json=hardDelete,proto3" json:"hard_delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	mi := &file_accounts_accountsapi_v1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_accountsapi_v1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_accounts_accountsapi_v1_api_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteAccountRequest) GetCommonId() string {
	if x != nil {
		return x.CommonId
	}
	return ""
}

func (x *DeleteAccountRequest) GetHardDelete() bool {
	if x != nil {
		return x.HardDelete
	}
	return false
}

// DeleteAccountResponse will let the caller know if the server deleted the account
type DeleteAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountResponse) Reset() {
	*x = DeleteAccountResponse{}
	mi := &file_accounts_accountsapi_v1_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountResponse) ProtoMessage() {}

func (x *DeleteAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_accountsapi_v1_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return file_accounts_accountsapi_v1_api_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteAccountResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_accounts_accountsapi_v1_api_proto protoreflect.FileDescriptor

const file_accounts_accountsapi_v1_api_proto_rawDesc = "" +
	"\n" +
	"!accounts/accountsapi/v1/api.proto\x12\x17accounts.accountsapi.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1agoogle/type/datetime.proto\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1daccounts/domain/account.proto\"\xfc\x01\n" +
	"\x14CreateAccountRequest\x12&\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tfirstName\x12$\n" +
	"\tlast_name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\blastName\x12#\n" +
	"\busername\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\busername\x12,\n" +
	"\remail_address\x18\x04 \x01(\tB\a\xbaH\x04r\x02`\x01R\femailAddress\x12+\n" +
	"\rclerk_user_id\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vclerkUserId\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\tR\x06gender\"5\n" +
	"\x14CreateAcountResponse\x12\x1d\n" +
	"\n" +
	"is_success\x18\x01 \x01(\bR\tisSuccess\"\x95\x01\n" +
	"\x11GetAccountRequest\x12*\n" +
	"\tcommon_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x00R\bcommonId\x88\x01\x01\x124\n" +
	"\remail_address\x18\x02 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x00r\x02`\x01H\x01R\femailAddress\x88\x01\x01B\f\n" +
	"\n" +
	"_common_idB\x10\n" +
	"\x0e_email_address\"H\n" +
	"\x12GetAccountResponse\x122\n" +
	"\aaccount\x18\x01 \x01(\v2\x18.accounts.domain.AccountR\aaccount\"^\n" +
	"\x14DeleteAccountRequest\x12%\n" +
	"\tcommon_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\bcommonId\x12\x1f\n" +
	"\vhard_delete\x18\x02 \x01(\bR\n" +
	"hardDelete\"R\n" +
	"\x15DeleteAccountResponse\x129\n" +
	"\n" +
	"deleted_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt2\xdc\x02\n" +
	"\x0eAccountService\x12o\n" +
	"\rCreateAccount\x12-.accounts.accountsapi.v1.CreateAccountRequest\x1a-.accounts.accountsapi.v1.CreateAcountResponse\"\x00\x12g\n" +
	"\n" +
	"GetAccount\x12*.accounts.accountsapi.v1.GetAccountRequest\x1a+.accounts.accountsapi.v1.GetAccountResponse\"\x00\x12p\n" +
	"\rDeleteAccount\x12-.accounts.accountsapi.v1.DeleteAccountRequest\x1a..accounts.accountsapi.v1.DeleteAccountResponse\"\x00B\xe6\x01\n" +
	"\x1bcom.accounts.accountsapi.v1B\bApiProtoP\x01Z?libs/backend/proto-gen/go/accounts/accountsapi/v1;accountsapiv1\xa2\x02\x03AAX\xaa\x02\x17Accounts.Accountsapi.V1\xca\x02\x17Accounts\\Accountsapi\\V1\xe2\x02#Accounts\\Accountsapi\\V1\\GPBMetadata\xea\x02\x19Accounts::Accountsapi::V1b\x06proto3"

var (
	file_accounts_accountsapi_v1_api_proto_rawDescOnce sync.Once
	file_accounts_accountsapi_v1_api_proto_rawDescData []byte
)

func file_accounts_accountsapi_v1_api_proto_rawDescGZIP() []byte {
	file_accounts_accountsapi_v1_api_proto_rawDescOnce.Do(func() {
		file_accounts_accountsapi_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_accounts_accountsapi_v1_api_proto_rawDesc), len(file_accounts_accountsapi_v1_api_proto_rawDesc)))
	})
	return file_accounts_accountsapi_v1_api_proto_rawDescData
}

var file_accounts_accountsapi_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_accounts_accountsapi_v1_api_proto_goTypes = []any{
	(*CreateAccountRequest)(nil),  // 0: accounts.accountsapi.v1.CreateAccountRequest
	(*CreateAcountResponse)(nil),  // 1: accounts.accountsapi.v1.CreateAcountResponse
	(*GetAccountRequest)(nil),     // 2: accounts.accountsapi.v1.GetAccountRequest
	(*GetAccountResponse)(nil),    // 3: accounts.accountsapi.v1.GetAccountResponse
	(*DeleteAccountRequest)(nil),  // 4: accounts.accountsapi.v1.DeleteAccountRequest
	(*DeleteAccountResponse)(nil), // 5: accounts.accountsapi.v1.DeleteAccountResponse
	(*domain.Account)(nil),        // 6: accounts.domain.Account
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_accounts_accountsapi_v1_api_proto_depIdxs = []int32{
	6, // 0: accounts.accountsapi.v1.GetAccountResponse.account:type_name -> accounts.domain.Account
	7, // 1: accounts.accountsapi.v1.DeleteAccountResponse.deleted_at:type_name -> google.protobuf.Timestamp
	0, // 2: accounts.accountsapi.v1.AccountService.CreateAccount:input_type -> accounts.accountsapi.v1.CreateAccountRequest
	2, // 3: accounts.accountsapi.v1.AccountService.GetAccount:input_type -> accounts.accountsapi.v1.GetAccountRequest
	4, // 4: accounts.accountsapi.v1.AccountService.DeleteAccount:input_type -> accounts.accountsapi.v1.DeleteAccountRequest
	1, // 5: accounts.accountsapi.v1.AccountService.CreateAccount:output_type -> accounts.accountsapi.v1.CreateAcountResponse
	3, // 6: accounts.accountsapi.v1.AccountService.GetAccount:output_type -> accounts.accountsapi.v1.GetAccountResponse
	5, // 7: accounts.accountsapi.v1.AccountService.DeleteAccount:output_type -> accounts.accountsapi.v1.DeleteAccountResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_accounts_accountsapi_v1_api_proto_init() }
func file_accounts_accountsapi_v1_api_proto_init() {
	if File_accounts_accountsapi_v1_api_proto != nil {
		return
	}
	file_accounts_accountsapi_v1_api_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_accounts_accountsapi_v1_api_proto_rawDesc), len(file_accounts_accountsapi_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_accounts_accountsapi_v1_api_proto_goTypes,
		DependencyIndexes: file_accounts_accountsapi_v1_api_proto_depIdxs,
		MessageInfos:      file_accounts_accountsapi_v1_api_proto_msgTypes,
	}.Build()
	File_accounts_accountsapi_v1_api_proto = out.File
	file_accounts_accountsapi_v1_api_proto_goTypes = nil
	file_accounts_accountsapi_v1_api_proto_depIdxs = nil
}
