// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: webhooks/inboundwebhooksapi/v1/api.proto

package inboundwebhooksapiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	v1 "libs/backend/proto-gen/go/common/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClerkUserAuthEventRequest defines the incoming data for the user event from
// the Clerk Webhooks
type ClerkUserAuthEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Object        string                 `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Data          *ClerkUser             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClerkUserAuthEventRequest) Reset() {
	*x = ClerkUserAuthEventRequest{}
	mi := &file_webhooks_inboundwebhooksapi_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClerkUserAuthEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClerkUserAuthEventRequest) ProtoMessage() {}

func (x *ClerkUserAuthEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webhooks_inboundwebhooksapi_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClerkUserAuthEventRequest.ProtoReflect.Descriptor instead.
func (*ClerkUserAuthEventRequest) Descriptor() ([]byte, []int) {
	return file_webhooks_inboundwebhooksapi_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *ClerkUserAuthEventRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ClerkUserAuthEventRequest) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ClerkUserAuthEventRequest) GetData() *ClerkUser {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_webhooks_inboundwebhooksapi_v1_api_proto protoreflect.FileDescriptor

const file_webhooks_inboundwebhooksapi_v1_api_proto_rawDesc = "" +
	"\n" +
	"(webhooks/inboundwebhooksapi/v1/api.proto\x12\x1ewebhooks.inboundwebhooksapi.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/protobuf/any.proto\x1a\x1bbuf/validate/validate.proto\x1a\x15common/v1/empty.proto\x1a/webhooks/inboundwebhooksapi/v1/clerk_auth.proto\"\x86\x01\n" +
	"\x19ClerkUserAuthEventRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12=\n" +
	"\x04data\x18\x03 \x01(\v2).webhooks.inboundwebhooksapi.v1.ClerkUserR\x04data2\xab\x01\n" +
	"\x1aInboundWebhooksAuthService\x12\x8c\x01\n" +
	"\x12ClerkAuthUserEvent\x129.webhooks.inboundwebhooksapi.v1.ClerkUserAuthEventRequest\x1a\x10.common.v1.Empty\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/webhooks/inbound/auth/userB\x97\x02\n" +
	"\"com.webhooks.inboundwebhooksapi.v1B\bApiProtoP\x01ZMlibs/backend/proto-gen/go/webhooks/inboundwebhooksapi/v1;inboundwebhooksapiv1\xa2\x02\x03WIX\xaa\x02\x1eWebhooks.Inboundwebhooksapi.V1\xca\x02\x1eWebhooks\\Inboundwebhooksapi\\V1\xe2\x02*Webhooks\\Inboundwebhooksapi\\V1\\GPBMetadata\xea\x02 Webhooks::Inboundwebhooksapi::V1b\x06proto3"

var (
	file_webhooks_inboundwebhooksapi_v1_api_proto_rawDescOnce sync.Once
	file_webhooks_inboundwebhooksapi_v1_api_proto_rawDescData []byte
)

func file_webhooks_inboundwebhooksapi_v1_api_proto_rawDescGZIP() []byte {
	file_webhooks_inboundwebhooksapi_v1_api_proto_rawDescOnce.Do(func() {
		file_webhooks_inboundwebhooksapi_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webhooks_inboundwebhooksapi_v1_api_proto_rawDesc), len(file_webhooks_inboundwebhooksapi_v1_api_proto_rawDesc)))
	})
	return file_webhooks_inboundwebhooksapi_v1_api_proto_rawDescData
}

var file_webhooks_inboundwebhooksapi_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_webhooks_inboundwebhooksapi_v1_api_proto_goTypes = []any{
	(*ClerkUserAuthEventRequest)(nil), // 0: webhooks.inboundwebhooksapi.v1.ClerkUserAuthEventRequest
	(*ClerkUser)(nil),                 // 1: webhooks.inboundwebhooksapi.v1.ClerkUser
	(*v1.Empty)(nil),                  // 2: common.v1.Empty
}
var file_webhooks_inboundwebhooksapi_v1_api_proto_depIdxs = []int32{
	1, // 0: webhooks.inboundwebhooksapi.v1.ClerkUserAuthEventRequest.data:type_name -> webhooks.inboundwebhooksapi.v1.ClerkUser
	0, // 1: webhooks.inboundwebhooksapi.v1.InboundWebhooksAuthService.ClerkAuthUserEvent:input_type -> webhooks.inboundwebhooksapi.v1.ClerkUserAuthEventRequest
	2, // 2: webhooks.inboundwebhooksapi.v1.InboundWebhooksAuthService.ClerkAuthUserEvent:output_type -> common.v1.Empty
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_webhooks_inboundwebhooksapi_v1_api_proto_init() }
func file_webhooks_inboundwebhooksapi_v1_api_proto_init() {
	if File_webhooks_inboundwebhooksapi_v1_api_proto != nil {
		return
	}
	file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webhooks_inboundwebhooksapi_v1_api_proto_rawDesc), len(file_webhooks_inboundwebhooksapi_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_webhooks_inboundwebhooksapi_v1_api_proto_goTypes,
		DependencyIndexes: file_webhooks_inboundwebhooksapi_v1_api_proto_depIdxs,
		MessageInfos:      file_webhooks_inboundwebhooksapi_v1_api_proto_msgTypes,
	}.Build()
	File_webhooks_inboundwebhooksapi_v1_api_proto = out.File
	file_webhooks_inboundwebhooksapi_v1_api_proto_goTypes = nil
	file_webhooks_inboundwebhooksapi_v1_api_proto_depIdxs = nil
}
