// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: webhooks/inboundwebhooksapi/v1/clerk_auth.proto

package inboundwebhooksapiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	_ "libs/backend/proto-gen/go/options"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClerkUserEventType defines the type of user event
// coming from the Clerk Webhooks
type ClerkUserEventType int32

const (
	ClerkUserEventType_CLERK_USER_EVENT_TYPE_UNKNOWN      ClerkUserEventType = 0
	ClerkUserEventType_CLERK_USER_EVENT_TYPE_USER_CREATED ClerkUserEventType = 1
)

// Enum value maps for ClerkUserEventType.
var (
	ClerkUserEventType_name = map[int32]string{
		0: "CLERK_USER_EVENT_TYPE_UNKNOWN",
		1: "CLERK_USER_EVENT_TYPE_USER_CREATED",
	}
	ClerkUserEventType_value = map[string]int32{
		"CLERK_USER_EVENT_TYPE_UNKNOWN":      0,
		"CLERK_USER_EVENT_TYPE_USER_CREATED": 1,
	}
)

func (x ClerkUserEventType) Enum() *ClerkUserEventType {
	p := new(ClerkUserEventType)
	*p = x
	return p
}

func (x ClerkUserEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClerkUserEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_enumTypes[0].Descriptor()
}

func (ClerkUserEventType) Type() protoreflect.EnumType {
	return &file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_enumTypes[0]
}

func (x ClerkUserEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClerkUserEventType.Descriptor instead.
func (ClerkUserEventType) EnumDescriptor() ([]byte, []int) {
	return file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_rawDescGZIP(), []int{0}
}

// ClerkUser represents the entire user object that is going
// to be passed in Clerk Authentication webhooks
type ClerkUser struct {
	state                 protoimpl.MessageState    `protogen:"open.v1"`
	Birthday              string                    `protobuf:"bytes,1,opt,name=birthday,proto3" json:"birthday,omitempty"`
	CreatedAt             uint64                    `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	EmailAddresses        []*ClerkUser_EmailAddress `protobuf:"bytes,3,rep,name=email_addresses,json=emailAddresses,proto3" json:"email_addresses,omitempty"`
	ExternalAccounts      []*anypb.Any              `protobuf:"bytes,4,rep,name=external_accounts,json=externalAccounts,proto3" json:"external_accounts,omitempty"`
	ExternalId            string                    `protobuf:"bytes,5,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	FirstName             string                    `protobuf:"bytes,6,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	Gender                string                    `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender,omitempty"`
	Id                    string                    `protobuf:"bytes,8,opt,name=id,proto3" json:"id,omitempty"`
	ImageUrl              string                    `protobuf:"bytes,9,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	LastName              string                    `protobuf:"bytes,10,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	LastSignInAt          uint64                    `protobuf:"varint,11,opt,name=last_sign_in_at,json=lastSignInAt,proto3" json:"last_sign_in_at,omitempty"`
	Object                string                    `protobuf:"bytes,12,opt,name=object,proto3" json:"object,omitempty"`
	PasswordEnabled       bool                      `protobuf:"varint,13,opt,name=password_enabled,json=passwordEnabled,proto3" json:"password_enabled,omitempty"`
	PhoneNumbers          []*ClerkUser_PhoneNumber  `protobuf:"bytes,14,rep,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"` // Changed from google.protobuf.Any to PhoneNumber
	PrimaryEmailAddressId string                    `protobuf:"bytes,15,opt,name=primary_email_address_id,json=primaryEmailAddressId,proto3" json:"primary_email_address_id,omitempty"`
	PrimaryPhoneNumberId  string                    `protobuf:"bytes,16,opt,name=primary_phone_number_id,json=primaryPhoneNumberId,proto3" json:"primary_phone_number_id,omitempty"`
	PrimaryWeb3WalletId   string                    `protobuf:"bytes,17,opt,name=primary_web3_wallet_id,json=primaryWeb3WalletId,proto3" json:"primary_web3_wallet_id,omitempty"`
	PrivateMetadata       map[string]*anypb.Any     `protobuf:"bytes,18,rep,name=private_metadata,json=privateMetadata,proto3" json:"private_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Changed keys from Any to string for clarity
	ProfileImageUrl       string                    `protobuf:"bytes,19,opt,name=profile_image_url,json=profileImageUrl,proto3" json:"profile_image_url,omitempty"`
	PublicMetadata        map[string]*anypb.Any     `protobuf:"bytes,20,rep,name=public_metadata,json=publicMetadata,proto3" json:"public_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Changed keys from Any to string for clarity
	TwoFactorEnabled      bool                      `protobuf:"varint,21,opt,name=two_factor_enabled,json=twoFactorEnabled,proto3" json:"two_factor_enabled,omitempty"`
	UnsafeMetadata        map[string]*anypb.Any     `protobuf:"bytes,22,rep,name=unsafe_metadata,json=unsafeMetadata,proto3" json:"unsafe_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Changed keys from Any to string for clarity
	UpdatedAt             uint64                    `protobuf:"varint,23,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Username              string                    `protobuf:"bytes,24,opt,name=username,proto3" json:"username,omitempty"`
	Web3Wallets           []*anypb.Any              `protobuf:"bytes,25,rep,name=web3_wallets,json=web3Wallets,proto3" json:"web3_wallets,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ClerkUser) Reset() {
	*x = ClerkUser{}
	mi := &file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClerkUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClerkUser) ProtoMessage() {}

func (x *ClerkUser) ProtoReflect() protoreflect.Message {
	mi := &file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClerkUser.ProtoReflect.Descriptor instead.
func (*ClerkUser) Descriptor() ([]byte, []int) {
	return file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ClerkUser) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *ClerkUser) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ClerkUser) GetEmailAddresses() []*ClerkUser_EmailAddress {
	if x != nil {
		return x.EmailAddresses
	}
	return nil
}

func (x *ClerkUser) GetExternalAccounts() []*anypb.Any {
	if x != nil {
		return x.ExternalAccounts
	}
	return nil
}

func (x *ClerkUser) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *ClerkUser) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ClerkUser) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *ClerkUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClerkUser) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ClerkUser) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ClerkUser) GetLastSignInAt() uint64 {
	if x != nil {
		return x.LastSignInAt
	}
	return 0
}

func (x *ClerkUser) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ClerkUser) GetPasswordEnabled() bool {
	if x != nil {
		return x.PasswordEnabled
	}
	return false
}

func (x *ClerkUser) GetPhoneNumbers() []*ClerkUser_PhoneNumber {
	if x != nil {
		return x.PhoneNumbers
	}
	return nil
}

func (x *ClerkUser) GetPrimaryEmailAddressId() string {
	if x != nil {
		return x.PrimaryEmailAddressId
	}
	return ""
}

func (x *ClerkUser) GetPrimaryPhoneNumberId() string {
	if x != nil {
		return x.PrimaryPhoneNumberId
	}
	return ""
}

func (x *ClerkUser) GetPrimaryWeb3WalletId() string {
	if x != nil {
		return x.PrimaryWeb3WalletId
	}
	return ""
}

func (x *ClerkUser) GetPrivateMetadata() map[string]*anypb.Any {
	if x != nil {
		return x.PrivateMetadata
	}
	return nil
}

func (x *ClerkUser) GetProfileImageUrl() string {
	if x != nil {
		return x.ProfileImageUrl
	}
	return ""
}

func (x *ClerkUser) GetPublicMetadata() map[string]*anypb.Any {
	if x != nil {
		return x.PublicMetadata
	}
	return nil
}

func (x *ClerkUser) GetTwoFactorEnabled() bool {
	if x != nil {
		return x.TwoFactorEnabled
	}
	return false
}

func (x *ClerkUser) GetUnsafeMetadata() map[string]*anypb.Any {
	if x != nil {
		return x.UnsafeMetadata
	}
	return nil
}

func (x *ClerkUser) GetUpdatedAt() uint64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ClerkUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ClerkUser) GetWeb3Wallets() []*anypb.Any {
	if x != nil {
		return x.Web3Wallets
	}
	return nil
}

// Verification represents the verification status of user attributes
type ClerkUser_Verification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Strategy      string                 `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClerkUser_Verification) Reset() {
	*x = ClerkUser_Verification{}
	mi := &file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClerkUser_Verification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClerkUser_Verification) ProtoMessage() {}

func (x *ClerkUser_Verification) ProtoReflect() protoreflect.Message {
	mi := &file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClerkUser_Verification.ProtoReflect.Descriptor instead.
func (*ClerkUser_Verification) Descriptor() ([]byte, []int) {
	return file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ClerkUser_Verification) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ClerkUser_Verification) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

// LinkedTo represents an entity linked to another object
type ClerkUser_LinkedTo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClerkUser_LinkedTo) Reset() {
	*x = ClerkUser_LinkedTo{}
	mi := &file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClerkUser_LinkedTo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClerkUser_LinkedTo) ProtoMessage() {}

func (x *ClerkUser_LinkedTo) ProtoReflect() protoreflect.Message {
	mi := &file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClerkUser_LinkedTo.ProtoReflect.Descriptor instead.
func (*ClerkUser_LinkedTo) Descriptor() ([]byte, []int) {
	return file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ClerkUser_LinkedTo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClerkUser_LinkedTo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// EmailAddress represents an email address of the user
type ClerkUser_EmailAddress struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	EmailAddress  string                  `protobuf:"bytes,1,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	Id            string                  `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	LinkedTo      []*ClerkUser_LinkedTo   `protobuf:"bytes,3,rep,name=linked_to,json=linkedTo,proto3" json:"linked_to,omitempty"` // Changed from google.protobuf.Any to LinkedTo
	Object        string                  `protobuf:"bytes,4,opt,name=object,proto3" json:"object,omitempty"`
	Verification  *ClerkUser_Verification `protobuf:"bytes,5,opt,name=verification,proto3" json:"verification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClerkUser_EmailAddress) Reset() {
	*x = ClerkUser_EmailAddress{}
	mi := &file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClerkUser_EmailAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClerkUser_EmailAddress) ProtoMessage() {}

func (x *ClerkUser_EmailAddress) ProtoReflect() protoreflect.Message {
	mi := &file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClerkUser_EmailAddress.ProtoReflect.Descriptor instead.
func (*ClerkUser_EmailAddress) Descriptor() ([]byte, []int) {
	return file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ClerkUser_EmailAddress) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

func (x *ClerkUser_EmailAddress) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClerkUser_EmailAddress) GetLinkedTo() []*ClerkUser_LinkedTo {
	if x != nil {
		return x.LinkedTo
	}
	return nil
}

func (x *ClerkUser_EmailAddress) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ClerkUser_EmailAddress) GetVerification() *ClerkUser_Verification {
	if x != nil {
		return x.Verification
	}
	return nil
}

// PhoneNumber represents a phone number associated with the user
type ClerkUser_PhoneNumber struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PhoneNumber             string                 `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	ReservedForSecondFactor bool                   `protobuf:"varint,3,opt,name=reserved_for_second_factor,json=reservedForSecondFactor,proto3" json:"reserved_for_second_factor,omitempty"`
	DefaultSecondFactor     bool                   `protobuf:"varint,4,opt,name=default_second_factor,json=defaultSecondFactor,proto3" json:"default_second_factor,omitempty"`
	LinkedTo                []*ClerkUser_LinkedTo  `protobuf:"bytes,5,rep,name=linked_to,json=linkedTo,proto3" json:"linked_to,omitempty"`
	BackupCodes             []string               `protobuf:"bytes,6,rep,name=backup_codes,json=backupCodes,proto3" json:"backup_codes,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ClerkUser_PhoneNumber) Reset() {
	*x = ClerkUser_PhoneNumber{}
	mi := &file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClerkUser_PhoneNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClerkUser_PhoneNumber) ProtoMessage() {}

func (x *ClerkUser_PhoneNumber) ProtoReflect() protoreflect.Message {
	mi := &file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClerkUser_PhoneNumber.ProtoReflect.Descriptor instead.
func (*ClerkUser_PhoneNumber) Descriptor() ([]byte, []int) {
	return file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_rawDescGZIP(), []int{0, 3}
}

func (x *ClerkUser_PhoneNumber) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClerkUser_PhoneNumber) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *ClerkUser_PhoneNumber) GetReservedForSecondFactor() bool {
	if x != nil {
		return x.ReservedForSecondFactor
	}
	return false
}

func (x *ClerkUser_PhoneNumber) GetDefaultSecondFactor() bool {
	if x != nil {
		return x.DefaultSecondFactor
	}
	return false
}

func (x *ClerkUser_PhoneNumber) GetLinkedTo() []*ClerkUser_LinkedTo {
	if x != nil {
		return x.LinkedTo
	}
	return nil
}

func (x *ClerkUser_PhoneNumber) GetBackupCodes() []string {
	if x != nil {
		return x.BackupCodes
	}
	return nil
}

var File_webhooks_inboundwebhooksapi_v1_clerk_auth_proto protoreflect.FileDescriptor

const file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_rawDesc = "" +
	"\n" +
	"/webhooks/inboundwebhooksapi/v1/clerk_auth.proto\x12\x1ewebhooks.inboundwebhooksapi.v1\x1a\x19google/protobuf/any.proto\x1a\x13options/enums.proto\"\xb3\x11\n" +
	"\tClerkUser\x12\x1a\n" +
	"\bbirthday\x18\x01 \x01(\tR\bbirthday\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x04R\tcreatedAt\x12_\n" +
	"\x0femail_addresses\x18\x03 \x03(\v26.webhooks.inboundwebhooksapi.v1.ClerkUser.EmailAddressR\x0eemailAddresses\x12A\n" +
	"\x11external_accounts\x18\x04 \x03(\v2\x14.google.protobuf.AnyR\x10externalAccounts\x12\x1f\n" +
	"\vexternal_id\x18\x05 \x01(\tR\n" +
	"externalId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x06 \x01(\tR\tfirstName\x12\x16\n" +
	"\x06gender\x18\a \x01(\tR\x06gender\x12\x0e\n" +
	"\x02id\x18\b \x01(\tR\x02id\x12\x1b\n" +
	"\timage_url\x18\t \x01(\tR\bimageUrl\x12\x1b\n" +
	"\tlast_name\x18\n" +
	" \x01(\tR\blastName\x12%\n" +
	"\x0flast_sign_in_at\x18\v \x01(\x04R\flastSignInAt\x12\x16\n" +
	"\x06object\x18\f \x01(\tR\x06object\x12)\n" +
	"\x10password_enabled\x18\r \x01(\bR\x0fpasswordEnabled\x12Z\n" +
	"\rphone_numbers\x18\x0e \x03(\v25.webhooks.inboundwebhooksapi.v1.ClerkUser.PhoneNumberR\fphoneNumbers\x127\n" +
	"\x18primary_email_address_id\x18\x0f \x01(\tR\x15primaryEmailAddressId\x125\n" +
	"\x17primary_phone_number_id\x18\x10 \x01(\tR\x14primaryPhoneNumberId\x123\n" +
	"\x16primary_web3_wallet_id\x18\x11 \x01(\tR\x13primaryWeb3WalletId\x12i\n" +
	"\x10private_metadata\x18\x12 \x03(\v2>.webhooks.inboundwebhooksapi.v1.ClerkUser.PrivateMetadataEntryR\x0fprivateMetadata\x12*\n" +
	"\x11profile_image_url\x18\x13 \x01(\tR\x0fprofileImageUrl\x12f\n" +
	"\x0fpublic_metadata\x18\x14 \x03(\v2=.webhooks.inboundwebhooksapi.v1.ClerkUser.PublicMetadataEntryR\x0epublicMetadata\x12,\n" +
	"\x12two_factor_enabled\x18\x15 \x01(\bR\x10twoFactorEnabled\x12f\n" +
	"\x0funsafe_metadata\x18\x16 \x03(\v2=.webhooks.inboundwebhooksapi.v1.ClerkUser.UnsafeMetadataEntryR\x0eunsafeMetadata\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x17 \x01(\x04R\tupdatedAt\x12\x1a\n" +
	"\busername\x18\x18 \x01(\tR\busername\x127\n" +
	"\fweb3_wallets\x18\x19 \x03(\v2\x14.google.protobuf.AnyR\vweb3Wallets\x1aB\n" +
	"\fVerification\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1a\n" +
	"\bstrategy\x18\x02 \x01(\tR\bstrategy\x1a.\n" +
	"\bLinkedTo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x1a\x88\x02\n" +
	"\fEmailAddress\x12#\n" +
	"\remail_address\x18\x01 \x01(\tR\femailAddress\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12O\n" +
	"\tlinked_to\x18\x03 \x03(\v22.webhooks.inboundwebhooksapi.v1.ClerkUser.LinkedToR\blinkedTo\x12\x16\n" +
	"\x06object\x18\x04 \x01(\tR\x06object\x12Z\n" +
	"\fverification\x18\x05 \x01(\v26.webhooks.inboundwebhooksapi.v1.ClerkUser.VerificationR\fverification\x1a\xa5\x02\n" +
	"\vPhoneNumber\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fphone_number\x18\x02 \x01(\tR\vphoneNumber\x12;\n" +
	"\x1areserved_for_second_factor\x18\x03 \x01(\bR\x17reservedForSecondFactor\x122\n" +
	"\x15default_second_factor\x18\x04 \x01(\bR\x13defaultSecondFactor\x12O\n" +
	"\tlinked_to\x18\x05 \x03(\v22.webhooks.inboundwebhooksapi.v1.ClerkUser.LinkedToR\blinkedTo\x12!\n" +
	"\fbackup_codes\x18\x06 \x03(\tR\vbackupCodes\x1aX\n" +
	"\x14PrivateMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\x1aW\n" +
	"\x13PublicMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\x1aW\n" +
	"\x13UnsafeMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01*w\n" +
	"\x12ClerkUserEventType\x12'\n" +
	"\x1dCLERK_USER_EVENT_TYPE_UNKNOWN\x10\x00\x1a\x04\x82\xb5\x18\x00\x128\n" +
	"\"CLERK_USER_EVENT_TYPE_USER_CREATED\x10\x01\x1a\x10\x82\xb5\x18\fuser.createdB\x9d\x02\n" +
	"\"com.webhooks.inboundwebhooksapi.v1B\x0eClerkAuthProtoP\x01ZMlibs/backend/proto-gen/go/webhooks/inboundwebhooksapi/v1;inboundwebhooksapiv1\xa2\x02\x03WIX\xaa\x02\x1eWebhooks.Inboundwebhooksapi.V1\xca\x02\x1eWebhooks\\Inboundwebhooksapi\\V1\xe2\x02*Webhooks\\Inboundwebhooksapi\\V1\\GPBMetadata\xea\x02 Webhooks::Inboundwebhooksapi::V1b\x06proto3"

var (
	file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_rawDescOnce sync.Once
	file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_rawDescData []byte
)

func file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_rawDescGZIP() []byte {
	file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_rawDescOnce.Do(func() {
		file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_rawDesc), len(file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_rawDesc)))
	})
	return file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_rawDescData
}

var file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_goTypes = []any{
	(ClerkUserEventType)(0),        // 0: webhooks.inboundwebhooksapi.v1.ClerkUserEventType
	(*ClerkUser)(nil),              // 1: webhooks.inboundwebhooksapi.v1.ClerkUser
	(*ClerkUser_Verification)(nil), // 2: webhooks.inboundwebhooksapi.v1.ClerkUser.Verification
	(*ClerkUser_LinkedTo)(nil),     // 3: webhooks.inboundwebhooksapi.v1.ClerkUser.LinkedTo
	(*ClerkUser_EmailAddress)(nil), // 4: webhooks.inboundwebhooksapi.v1.ClerkUser.EmailAddress
	(*ClerkUser_PhoneNumber)(nil),  // 5: webhooks.inboundwebhooksapi.v1.ClerkUser.PhoneNumber
	nil,                            // 6: webhooks.inboundwebhooksapi.v1.ClerkUser.PrivateMetadataEntry
	nil,                            // 7: webhooks.inboundwebhooksapi.v1.ClerkUser.PublicMetadataEntry
	nil,                            // 8: webhooks.inboundwebhooksapi.v1.ClerkUser.UnsafeMetadataEntry
	(*anypb.Any)(nil),              // 9: google.protobuf.Any
}
var file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_depIdxs = []int32{
	4,  // 0: webhooks.inboundwebhooksapi.v1.ClerkUser.email_addresses:type_name -> webhooks.inboundwebhooksapi.v1.ClerkUser.EmailAddress
	9,  // 1: webhooks.inboundwebhooksapi.v1.ClerkUser.external_accounts:type_name -> google.protobuf.Any
	5,  // 2: webhooks.inboundwebhooksapi.v1.ClerkUser.phone_numbers:type_name -> webhooks.inboundwebhooksapi.v1.ClerkUser.PhoneNumber
	6,  // 3: webhooks.inboundwebhooksapi.v1.ClerkUser.private_metadata:type_name -> webhooks.inboundwebhooksapi.v1.ClerkUser.PrivateMetadataEntry
	7,  // 4: webhooks.inboundwebhooksapi.v1.ClerkUser.public_metadata:type_name -> webhooks.inboundwebhooksapi.v1.ClerkUser.PublicMetadataEntry
	8,  // 5: webhooks.inboundwebhooksapi.v1.ClerkUser.unsafe_metadata:type_name -> webhooks.inboundwebhooksapi.v1.ClerkUser.UnsafeMetadataEntry
	9,  // 6: webhooks.inboundwebhooksapi.v1.ClerkUser.web3_wallets:type_name -> google.protobuf.Any
	3,  // 7: webhooks.inboundwebhooksapi.v1.ClerkUser.EmailAddress.linked_to:type_name -> webhooks.inboundwebhooksapi.v1.ClerkUser.LinkedTo
	2,  // 8: webhooks.inboundwebhooksapi.v1.ClerkUser.EmailAddress.verification:type_name -> webhooks.inboundwebhooksapi.v1.ClerkUser.Verification
	3,  // 9: webhooks.inboundwebhooksapi.v1.ClerkUser.PhoneNumber.linked_to:type_name -> webhooks.inboundwebhooksapi.v1.ClerkUser.LinkedTo
	9,  // 10: webhooks.inboundwebhooksapi.v1.ClerkUser.PrivateMetadataEntry.value:type_name -> google.protobuf.Any
	9,  // 11: webhooks.inboundwebhooksapi.v1.ClerkUser.PublicMetadataEntry.value:type_name -> google.protobuf.Any
	9,  // 12: webhooks.inboundwebhooksapi.v1.ClerkUser.UnsafeMetadataEntry.value:type_name -> google.protobuf.Any
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_init() }
func file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_init() {
	if File_webhooks_inboundwebhooksapi_v1_clerk_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_rawDesc), len(file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_goTypes,
		DependencyIndexes: file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_depIdxs,
		EnumInfos:         file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_enumTypes,
		MessageInfos:      file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_msgTypes,
	}.Build()
	File_webhooks_inboundwebhooksapi_v1_clerk_auth_proto = out.File
	file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_goTypes = nil
	file_webhooks_inboundwebhooksapi_v1_clerk_auth_proto_depIdxs = nil
}
