// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: options/enums.proto

package options

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_options_enums_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50000,
		Name:          "options.string_value",
		Tag:           "bytes,50000,opt,name=string_value",
		Filename:      "options/enums.proto",
	},
}

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional string string_value = 50000;
	E_StringValue = &file_options_enums_proto_extTypes[0] // Use a unique number
)

var File_options_enums_proto protoreflect.FileDescriptor

const file_options_enums_proto_rawDesc = "" +
	"\n" +
	"\x13options/enums.proto\x12\aoptions\x1a google/protobuf/descriptor.proto:I\n" +
	"\fstring_value\x12!.google.protobuf.EnumValueOptions\x18І\x03 \x01(\tR\vstringValue\x88\x01\x01Bx\n" +
	"\vcom.optionsB\n" +
	"EnumsProtoP\x01Z!libs/backend/proto-gen/go/options\xa2\x02\x03OXX\xaa\x02\aOptions\xca\x02\aOptions\xe2\x02\x13Options\\GPBMetadata\xea\x02\aOptionsb\x06proto3"

var file_options_enums_proto_goTypes = []any{
	(*descriptorpb.EnumValueOptions)(nil), // 0: google.protobuf.EnumValueOptions
}
var file_options_enums_proto_depIdxs = []int32{
	0, // 0: options.string_value:extendee -> google.protobuf.EnumValueOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_options_enums_proto_init() }
func file_options_enums_proto_init() {
	if File_options_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_options_enums_proto_rawDesc), len(file_options_enums_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_options_enums_proto_goTypes,
		DependencyIndexes: file_options_enums_proto_depIdxs,
		ExtensionInfos:    file_options_enums_proto_extTypes,
	}.Build()
	File_options_enums_proto = out.File
	file_options_enums_proto_goTypes = nil
	file_options_enums_proto_depIdxs = nil
}
