fullname: inbound-webhooks-api
replicaCount: 1
autoscaling:
  enabled: false
labels:
  app: inbound-webhooks-api
service:
  type: ClusterIP
  port: 3000
image:
  repository: inbound-webhooks-api
  tag: latest
  pullPolicy: Never
