# fly.toml app configuration file generated for accounts-worker-prod-challah-social on 2025-01-25T13:29:31-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'accounts-worker-prod-challah-social'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'
  ignorefile = '.dockerignore'

[[services]]
  protocol = ''
  internal_port = 0
  ports = []

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[metrics]]
  port = 3000
  path = '/metrics'
  https = false
