# fly.toml app configuration file generated for profile-api-prod on 2025-05-31T13:14:48-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'profile-api-prod'
primary_region = 'ewr'

[build]
  dockerfile = 'Dockerfile'

[[services]]
  protocol = ''
  internal_port = 0
  ports = []

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[metrics]]
  port = 3000
  path = '/metrics'
