version: '3.9'
services:
  inbound-webhooks-api:
    image: career-cue/inbound-webhooks-api
    container_name: career-cue-inbound-webhooks-api
    build:
      context: ../../..
      dockerfile: ./apps/services/inbound-webhooks-api/Dockerfile
    ports:
      - 3001:3000
