// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: accounts/domain/account.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Account defines the account domain model
type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommonId      string                 `protobuf:"bytes,1,opt,name=common_id,json=commonId,proto3" json:"common_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	EmailAddress  string                 `protobuf:"bytes,3,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_accounts_domain_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_domain_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_accounts_domain_account_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetCommonId() string {
	if x != nil {
		return x.CommonId
	}
	return ""
}

func (x *Account) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Account) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Account) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_accounts_domain_account_proto protoreflect.FileDescriptor

const file_accounts_domain_account_proto_rawDesc = "" +
	"\n" +
	"\x1daccounts/domain/account.proto\x12\x0faccounts.domain\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdd\x01\n" +
	"\aAccount\x12\x1b\n" +
	"\tcommon_id\x18\x01 \x01(\tR\bcommonId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12#\n" +
	"\remail_address\x18\x03 \x01(\tR\femailAddress\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\xab\x01\n" +
	"\x13com.accounts.domainB\fAccountProtoP\x01Z)libs/backend/proto-gen/go/accounts/domain\xa2\x02\x03ADX\xaa\x02\x0fAccounts.Domain\xca\x02\x0fAccounts\\Domain\xe2\x02\x1bAccounts\\Domain\\GPBMetadata\xea\x02\x10Accounts::Domainb\x06proto3"

var (
	file_accounts_domain_account_proto_rawDescOnce sync.Once
	file_accounts_domain_account_proto_rawDescData []byte
)

func file_accounts_domain_account_proto_rawDescGZIP() []byte {
	file_accounts_domain_account_proto_rawDescOnce.Do(func() {
		file_accounts_domain_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_accounts_domain_account_proto_rawDesc), len(file_accounts_domain_account_proto_rawDesc)))
	})
	return file_accounts_domain_account_proto_rawDescData
}

var file_accounts_domain_account_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_accounts_domain_account_proto_goTypes = []any{
	(*Account)(nil),               // 0: accounts.domain.Account
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_accounts_domain_account_proto_depIdxs = []int32{
	1, // 0: accounts.domain.Account.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: accounts.domain.Account.updated_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_accounts_domain_account_proto_init() }
func file_accounts_domain_account_proto_init() {
	if File_accounts_domain_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_accounts_domain_account_proto_rawDesc), len(file_accounts_domain_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_accounts_domain_account_proto_goTypes,
		DependencyIndexes: file_accounts_domain_account_proto_depIdxs,
		MessageInfos:      file_accounts_domain_account_proto_msgTypes,
	}.Build()
	File_accounts_domain_account_proto = out.File
	file_accounts_domain_account_proto_goTypes = nil
	file_accounts_domain_account_proto_depIdxs = nil
}
