app = 'accounts-graphql-prod'

[[services]]
primary_region = 'ewr'

[build]
dockerfile = "Dockerfile"



[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[[machines]]
restart_policy = "always"

[metrics]
port = 3000
path = "/metrics" # default for most prometheus exporters
